export const ADD_TO_WATCHLIST = "ADD_TO_WATCH_LIST";
export const REMOVE_FROM_WATCH_LIST = "REMOVE_FROM_WATCH_LIST";
export const MOVE_TO_WATCH_LIST = "MOVE_TO_WATCH_LIST";
export const ADD_TO_WATCHED = "ADD_TO_WATCHED";
export const REMOVE_FROM_WATCHED = "REMOVE_FROM_WATCHED";
